# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a022f7b1d21aa62cccd7c6ece3520b7b13b4baa5b19386360ee38a1174b28e178a10a0e3bc4d645cd8bdfcc09491c8a108a6446ba97d3d05f74d9ac637013577

test:
  secret_key_base: dc95236d037fc191cecaa08000151543079679de1545d93697329165db413c9c3d4ded86a23c1a07da465c6f38803e5476c535c84023d15044fed12d6e429038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
